In [1]:
# Eventi: acceso il ventilatore alle 17.52, corridoio verso la stanza
# Eventi: acceso il ventilatore alle 18.04, chiusa porta. ventilatore fuori dalla stanza 
# porta apert: 6.53

In [2]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from influxdb_client import InfluxDBClient
import os
from dotenv import load_dotenv
from utils import fetch_influx_data, query

Configurazione caricata correttamente!
 URL: http://10.205.116.209:8086 |  Bucket: monitoraggio_pi

In [2]:
test = fetch_influx_data( query=query)
test

,result,table,_start,_stop,_time,_measurement,host,stanza,percepita,temperatura,umidita
0,_result,0,2026-07-30 14:12:44.310056+00:00,2026-07-30 17:12:44.310056+00:00,2026-07-30 15:42:00.604391+00:00,ambiente,raspberry_pi_4,camera,37.6,34.7,43.0
1,_result,0,2026-07-30 14:12:44.310056+00:00,2026-07-30 17:12:44.310056+00:00,2026-07-30 15:42:07.328718+00:00,ambiente,raspberry_pi_4,camera,37.6,34.7,43.0
2,_result,0,2026-07-30 14:12:44.310056+00:00,2026-07-30 17:12:44.310056+00:00,2026-07-30 15:42:12.597040+00:00,ambiente,raspberry_pi_4,camera,37.6,34.7,43.0
3,_result,0,2026-07-30 14:12:44.310056+00:00,2026-07-30 17:12:44.310056+00:00,2026-07-30 15:42:23.124992+00:00,ambiente,raspberry_pi_4,camera,37.6,34.7,43.0
4,_result,0,2026-07-30 14:12:44.310056+00:00,2026-07-30 17:12:44.310056+00:00,2026-07-30 15:42:28.396898+00:00,ambiente,raspberry_pi_4,camera,37.6,34.7,43.0
...,...,...,...,...,...,...,...,...,...,...,...
989,_result,0,2026-07-30 14:12:44.310056+00:00,2026-07-30 17:12:44.310056+00:00,2026-07-30 17:12:20.912116+00:00,ambiente,raspberry_pi_4,camera,37.0,34.7,41.0
990,_result,0,2026-07-30 14:12:44.310056+00:00,2026-07-30 17:12:44.310056+00:00,2026-07-30 17:12:26.172425+00:00,ambiente,raspberry_pi_4,camera,37.0,34.7,41.0
991,_result,0,2026-07-30 14:12:44.310056+00:00,2026-07-30 17:12:44.310056+00:00,2026-07-30 17:12:31.442259+00:00,ambiente,raspberry_pi_4,camera,37.0,34.7,41.0
992,_result,0,2026-07-30 14:12:44.310056+00:00,2026-07-30 17:12:44.310056+00:00,2026-07-30 17:12:36.702289+00:00,ambiente,raspberry_pi_4,camera,37.0,34.7,41.0
993,_result,0,2026-07-30 14:12:44.310056+00:00,2026-07-30 17:12:44.310056+00:00,2026-07-30 17:12:41.972293+00:00,ambiente,raspberry_pi_4,camera,37.0,34.7,41.0

In [3]:
test.to_csv("data/days/30-luglio-2026.csv")

In [3]:
read = pd.read_csv("data/days/30-luglio-2026.csv")
read

,Unnamed: 0,result,table,_start,_stop,_time,_measurement,host,stanza,percepita,temperatura,umidita
0,0,_result,0,2026-07-30 14:12:44.310056+00:00,2026-07-30 17:12:44.310056+00:00,2026-07-30 15:42:00.604391+00:00,ambiente,raspberry_pi_4,camera,37.6,34.7,43.0
1,1,_result,0,2026-07-30 14:12:44.310056+00:00,2026-07-30 17:12:44.310056+00:00,2026-07-30 15:42:07.328718+00:00,ambiente,raspberry_pi_4,camera,37.6,34.7,43.0
2,2,_result,0,2026-07-30 14:12:44.310056+00:00,2026-07-30 17:12:44.310056+00:00,2026-07-30 15:42:12.597040+00:00,ambiente,raspberry_pi_4,camera,37.6,34.7,43.0
3,3,_result,0,2026-07-30 14:12:44.310056+00:00,2026-07-30 17:12:44.310056+00:00,2026-07-30 15:42:23.124992+00:00,ambiente,raspberry_pi_4,camera,37.6,34.7,43.0
4,4,_result,0,2026-07-30 14:12:44.310056+00:00,2026-07-30 17:12:44.310056+00:00,2026-07-30 15:42:28.396898+00:00,ambiente,raspberry_pi_4,camera,37.6,34.7,43.0
...,...,...,...,...,...,...,...,...,...,...,...,...
989,989,_result,0,2026-07-30 14:12:44.310056+00:00,2026-07-30 17:12:44.310056+00:00,2026-07-30 17:12:20.912116+00:00,ambiente,raspberry_pi_4,camera,37.0,34.7,41.0
990,990,_result,0,2026-07-30 14:12:44.310056+00:00,2026-07-30 17:12:44.310056+00:00,2026-07-30 17:12:26.172425+00:00,ambiente,raspberry_pi_4,camera,37.0,34.7,41.0
991,991,_result,0,2026-07-30 14:12:44.310056+00:00,2026-07-30 17:12:44.310056+00:00,2026-07-30 17:12:31.442259+00:00,ambiente,raspberry_pi_4,camera,37.0,34.7,41.0
992,992,_result,0,2026-07-30 14:12:44.310056+00:00,2026-07-30 17:12:44.310056+00:00,2026-07-30 17:12:36.702289+00:00,ambiente,raspberry_pi_4,camera,37.0,34.7,41.0
993,993,_result,0,2026-07-30 14:12:44.310056+00:00,2026-07-30 17:12:44.310056+00:00,2026-07-30 17:12:41.972293+00:00,ambiente,raspberry_pi_4,camera,37.0,34.7,41.0

In [ ]:
# Eventi : 
class Evento:
    def __init__(self, description, time, color='b'):

        self.description = description
        self.time = time
        self.color = color 

allEvents = [
    Evento('corr verso stanza', pd.to_datetime("TODO_"),
]